### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by SamStudio8** [cvdelannoy/poreTally#2]
Hi there!
Can you clarify the LICENSE for `poreTally`? Once you've [chosen a suitable one](https://choosealicense.com/), then [you can add a LICENSE to your Github repo from the web](https://help.github.com/articles/adding-a-license-to-a-repository/).

**Comment by cvdelannoy** [comment]
Added, thanks!

**Comment by SamStudio8** [comment]
MIT, a fine choice! Thanks!
