### ISSUE TITLE
question - illumina reads

### ISSUE THREAD

**Issue by thsyd** [cvdelannoy/poreTally#4]
Hi,
is there an argument for illumina read sets. eg to run pilon or racon with illumina reads?
eg poretally -i1 -i2

**Comment by cvdelannoy** [comment]
Good question, not yet! It'd be a valuable addition and shouldn't take much time to put in so I plan to do it soon.

**Comment by cvdelannoy** [comment]
You can now add, one or more directories containing short accurate reads with the -a option. I've added a minmap2 + miniasm + pilon pipeline to try it out with.
