### ISSUE TITLE
FASTA Support 

### ISSUE THREAD

**Issue by jmsutton2** [cvdelannoy/poreTally#6]
Hi,

Is there a way to run poreTally with FASTA files rather than FASTQ? Most of the assemblers support FASTA inputs on their own. 

Thanks,

John Sutton

**Comment by cvdelannoy** [comment]
Hi John,

Thanks for the suggestion! You can now submit fasta reads using --reads-fastq /path/to/reads

The report won't contain read quality metrics, but everything else should work fine.
